services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - prod.env
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
