services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - prod.env
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    env_file:
      - prod.env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
