services:
  db:
    user: 1000:1000
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: postgres
      POSTGRES_DB: somedb
    ports:
      - 54321:5432
    volumes:
      - ./data:/var/lib/postgresql/data